### ISSUE TITLE
Enable HTTPS for website

### ISSUE THREAD

**Issue by hlapp** [biosql/biosql.github.io#12]
Through a partnership with Let's Encrypt [Github allows HTTPS for custom domains since May 1](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/). Let's enable this here.

SSL issuance may need triggering, see bioperl/bioperl.github.io#45.

**Comment by peterjc** [comment]
I was meaning to look at this for biopython.org etc, so if this works for biosql.org we can roll this out more widely 👍 

https://github.com/biopython/biopython.github.io/issues/133

**Comment by hlapp** [comment]
You mean if this works for bioperl.org? I'm in the process of making the DNS changes for biosql.org and biojava.org, so those aren't ready yet. (SSL certs for custom apex domains require changing DNS A records.)

**Comment by peterjc** [comment]
Yes - I missed that BioPerl was actually the first test case, and now works https://bioperl.org

**Comment by hlapp** [comment]
DNS changed. SSL cert issuance triggered through 1d21705e3a08cdc2d90712dcf324dbd869c558a4 and 9a10c582e69ef2a9ad866e94ab7683fd7b84a152. HTTPS now enforced, seems to work! 🎉
