### ISSUE TITLE
Eye-balling all the converted pages

### ISSUE THREAD

**Issue by peterjc** [biosql/biosql.github.io#3]
Do all the pages look OK in terms of the markdown rendering from MediaWiki?
- [x] http://biosql.org/wiki/Annotation_Mapping
- [x] http://biosql.org/wiki/BioJava_BioSQL_ORM
- [x] http://biosql.org/wiki/Downloads
- [x] http://biosql.org/wiki/Enhancement_Requests
- [x] http://biosql.org/wiki/Extensions
- [x] http://biosql.org/wiki/Main_Page
- [x] http://biosql.org/wiki/Optimizations
- [x] http://biosql.org/wiki/PhyloDBSchema
- [x] http://biosql.org/wiki/Releases
- [x] http://biosql.org/wiki/Schema_Overview
- [x] http://biosql.org/wiki/Uses

**Comment by hlapp** [comment]
Checked all. Fixed the table formatting in Annotation_Mapping (370cbdeddee89192a11b6bbee6b828ef1d22fda2) and created a new issue for the Biojava to BioSQL ORM (#8).
