### ISSUE TITLE
Checking all the URLs still work

### ISSUE THREAD

**Issue by peterjc** [biosql/biosql.github.io#6]
We need to spider the site and find any broken internal or external links.

**Comment by greed2411** [comment]
Hi. I'm new to open source but still thought this thing I could try, I want to help and try to learn, I've proposed a PR with results.md in it which has the list of broken links in the domain

link for PR : https://github.com/biosql/biosql.github.io/pull/10 @peterjc

**Comment by peterjc** [comment]
Here is the report from @Jaiimmortal:

## Broken links of [BioSQL](http://biosql.org/)

Processed links: 117 / 117
Finished in: 3 minutes 13 seconds
Depth = 10

Covering issues : 
 * [Checking all the URLs still work](https://github.com/biosql/biosql.github.io/issues/6) - The whole md is for that issue
 * [Include URL checking in TravisCI setup](https://github.com/biosql/biosql.github.io/issues/4) - No broken links


***Broken links (10)***

1. [http://biosql.org/wiki/Main_Page](http://biosql.org/wiki/Main_Page)

  * [404]  http://open-bio.org/mailman/listinfo/biosql-l
  * [404]  http://open-bio.org/mailman/listinfo/biosql-guts-l

2. [http://biosql.org/wiki/Releases](http://biosql.org/wiki/Releases)

  * [ConnectFailure]  http://code.open-bio.org/svnweb/index.cgi/biosql/browse/biosql-schema/trunk/doc/biopython
  * [ConnectFailure]  http://code.open-bio.org/svnweb/index.cgi/biosql/checkout/biosql-schema/trunk/doc/biopython/python_biosql_basic.pdf
  * [ConnectFailure]  http://code.open-bio.org/svnweb/index.cgi/biosql/checkout/biosql-schema/trunk/doc/bj_and_bsql_oracle_howto.htm

3. [http://biosql.org/wiki/Enhancement_Requests](http://biosql.org/wiki/Enhancement_Requests)

  * [301 » ConnectFailure]  http://www.ebi.ac.uk/embl/Documentation/User_manual/usrman.html#3_4_14
  * [301 » ConnectFailure]  http://www.ebi.ac.uk/embl/Documentation/User_manual/usrman.html#3_4_13

4. [http://biosql.org/wiki/BioJava_BioSQL_ORM ](http://biosql.org/wiki/BioJava_BioSQL_ORM )

  * [404]  http://biojava.org/wikis/BioJava:BioJavaXDocs/
  * [ConnectFailure]  http://code.open-bio.org/svnweb/index.cgi/biojava/browse/biojava-live/trunk/src/org/biojavax/bio/db/biosql/pg
  * [ConnectFailure]  http://code.open-bio.org/svnweb/index.cgi/biojava/browse/biojava-live/trunk/src/org/biojavax/bio/db/biosql/oracle
  * [ConnectFailure]  http://code.open-bio.org/svnweb/index.cgi/biojava/browse/biojava-live/trunk/src/org/biojavax/bio/db/biosql/mysql
  * [ConnectFailure]  http://code.open-bio.org/svnweb/index.cgi/biojava/browse/biojava-live/trunk/src/org/biojavax/bio/db/biosql/hsqldb

5. [http://biosql.org/wiki/PhyloDBSchema](http://biosql.org/wiki/PhyloDBSchema)

  * [NameResolutionFailure]  http://rs18.rapidshare.com/files/4441805/Trees_and_Hierarchies_in_SQL_for_Smarties.pdf

6. [https://biosql.org/wiki/Main_Page](https://biosql.org/wiki/Main_Page)

  * [404]  http://open-bio.org/mailman/listinfo/biosql-l
  * [404]  http://open-bio.org/mailman/listinfo/biosql-guts-l

7. [https://biosql.org/wiki/Releases](https://biosql.org/wiki/Releases)

  * [ConnectFailure]  http://code.open-bio.org/svnweb/index.cgi/biosql/browse/biosql-schema/trunk/doc/biopython
  * [ConnectFailure]  http://code.open-bio.org/svnweb/index.cgi/biosql/checkout/biosql-schema/trunk/doc/biopython/python_biosql_basic.pdf
  * [ConnectFailure]  http://code.open-bio.org/svnweb/index.cgi/biosql/checkout/biosql-schema/trunk/doc/bj_and_bsql_oracle_howto.htm

8. [https://biosql.org/wiki/Enhancement_Requests](https://biosql.org/wiki/Enhancement_Requests)

  * [301 » ConnectFailure]  http://www.ebi.ac.uk/embl/Documentation/User_manual/usrman.html#3_4_14
  * [301 » ConnectFailure]  http://www.ebi.ac.uk/embl/Documentation/User_manual/usrman.html#3_4_13

9. [https://biosql.org/wiki/BioJava_BioSQL_ORM](https://biosql.org/wiki/BioJava_BioSQL_ORM)

  * [404]  http://biojava.org/wikis/BioJava:BioJavaXDocs/
  * [ConnectFailure]  http://code.open-bio.org/svnweb/index.cgi/biojava/browse/biojava-live/trunk/src/org/biojavax/bio/db/biosql/pg
  * [ConnectFailure]  http://code.open-bio.org/svnweb/index.cgi/biojava/browse/biojava-live/trunk/src/org/biojavax/bio/db/biosql/oracle
  * [ConnectFailure]  http://code.open-bio.org/svnweb/index.cgi/biojava/browse/biojava-live/trunk/src/org/biojavax/bio/db/biosql/mysql
  * [ConnectFailure]  http://code.open-bio.org/svnweb/index.cgi/biojava/browse/biojava-live/trunk/src/org/biojavax/bio/db/biosql/hsqldb

10. [https://biosql.org/wiki/PhyloDBSchema](https://biosql.org/wiki/PhyloDBSchea) 

  * [NameResolutionFailure]  http://rs18.rapidshare.com/files/4441805/Trees_and_Hierarchies_in_SQL_for_Smarties.pdf

**Comment by peterjc** [comment]
The mailing lists are no longer available on the main server, that likely used to have a redirection - which we may be able to reinstate? CC @hlapp 

Anyway, to fix http://biosql.org/wiki/Main_Page edit https://github.com/biosql/biosql.github.io/blob/master/wiki/Main_Page.md and for example replace http://open-bio.org/mailman/listinfo/biosql-l with
http://mailman.open-bio.org/mailman/listinfo/biosql-l

Many of these broken links are to our old SVN server, which is no longer used.  Both BioSQL and BioJava are now on GitHub and these equivalent links would be somewhere under https://github.com/biosql/biosql and https://github.com/biojava/biojava or perhaps https://github.com/biojava/biojava-legacy

**Comment by greed2411** [comment]
Hello again,
  Sorry for earlier, but the actual missing links are:

1. http://biosql.org/wiki/Main_Page

[404] http://open-bio.org/mailman/listinfo/biosql-l
[404] http://open-bio.org/mailman/listinfo/biosql-guts-l

2. http://biosql.org/wiki/Releases

[ConnectFailure] http://code.open-bio.org/svnweb/index.cgi/biosql/browse/biosql-schema/trunk/doc/biopython
[ConnectFailure] http://code.open-bio.org/svnweb/index.cgi/biosql/checkout/biosql-schema/trunk/doc/biopython/python_biosql_basic.pdf
[ConnectFailure] http://code.open-bio.org/svnweb/index.cgi/biosql/checkout/biosql-schema/trunk/doc/bj_and_bsql_oracle_howto.htm

3. http://biosql.org/wiki/Enhancement_Requests

[301 » ConnectFailure] http://www.ebi.ac.uk/embl/Documentation/User_manual/usrman.html#3_4_14
[301 » ConnectFailure] http://www.ebi.ac.uk/embl/Documentation/User_manual/usrman.html#3_4_13

4. http://biosql.org/wiki/BioJava_BioSQL_ORM

[404] http://biojava.org/wikis/BioJava:BioJavaXDocs/
[ConnectFailure] http://code.open-bio.org/svnweb/index.cgi/biojava/browse/biojava-live/trunk/src/org/biojavax/bio/db/biosql/pg
[ConnectFailure] http://code.open-bio.org/svnweb/index.cgi/biojava/browse/biojava-live/trunk/src/org/biojavax/bio/db/biosql/oracle
[ConnectFailure] http://code.open-bio.org/svnweb/index.cgi/biojava/browse/biojava-live/trunk/src/org/biojavax/bio/db/biosql/mysql
[ConnectFailure] http://code.open-bio.org/svnweb/index.cgi/biojava/browse/biojava-live/trunk/src/org/biojavax/bio/db/biosql/hsqldb

5. http://biosql.org/wiki/PhyloDBSchema

[NameResolutionFailure] http://rs18.rapidshare.com/files/4441805/Trees_and_Hierarchies_in_SQL_for_Smarties.pdf

@peterjc i apologize once again, these are the actual links, and they have been fixed and here is the PR:
https://github.com/biosql/biosql.github.io/pull/11

**Comment by hlapp** [comment]
> The mailing lists are no longer available on the main server, that likely used to have a redirection - which we may be able to reinstate? CC @hlapp

I wish I could but the shared hosting server seems to be treating the `/mailman` prefix special. I can get `/mailman2` to redirect properly, but somehow `/mailman` seems to get intercepted before it gets to the apache redirect directives.

**Comment by hlapp** [comment]
FYI, I submitted a support ticket to Namecheap, but I'm not holding my hopes high that their interception can be disabled.

**Comment by hlapp** [comment]
Thanks @Jaiimmortal for your help! Much appreciated.

**Comment by greed2411** [comment]
@hlapp  the pleasure is mine , you don't know how happy I am today , This is the first PR that got merged, I'm grateful.
